---
- name: Run Front-End
  docker_container:
    name: devops-front
    image: cheetaheim/tp-devops-frontend:latest
    state: started
    ports:
      - "80:80"  
    networks:
      - name: app-network
    pull: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
 