---
- name: Launch Database
  docker_container:
    name: postgres-db
    image: cheetaheim/tp-devops-postgres:latest
    state: started
    env:
      POSTGRES_DB: "db"
      POSTGRES_USER: "usr"  
      POSTGRES_PASSWORD: "pwd"
    networks:
      - name: app-network
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

