---
- name: Launch Database
  community.general.docker_container:
    name: postgres-db
    image: cheetaheim/postgres-db:latest
    state: started
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    networks:
      - name: app-network
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

