---
- name: Run App
  docker_container:
    name: simple-api-student
    image: cheetaheim/tp-devops-simple-api:latest
    state: started
    env:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_usr }}"
      POSTGRES_PASSWORD: "{{ postgres_pwd }}"
      POSTGRES_HOSTNAME: "{{ postgres_container }}"
      POSTGRES_PORT: "{{ postgres_port }}"

    networks:
      - name: app-network
    pull: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

