- name: Run Proxy
  docker_container:
    name: httpd-container
    image: cheetaheim/tp-devops-httpd:latest
    ports:
      - "80:80"
    state: started
    networks:
      - name: app-network
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
