---
- name: Déploiement de l'application
  hosts: all
  gather_facts: false
  become: yes

  vars:
    postgres_db: "db"
    postgres_usr: "usr"
    postgres_pwd: "pwd"
    postgres_container: "postgres-db"
    postgres_port: "5432"

  roles:
    - install-docker
    - create-network
    - launch-database
    - launch-app
    - launch-front
    - launch-proxy
