
# Use the official OpenJDK image as the base image
FROM openjdk:11-jre-slim

# Set the working directory in the container
WORKDIR /app

# TODO: Copy the compiled Java bytecode (Main.class) to the container
COPY Main.class /app/

# TODO: Run the Java application
CMD ["java", "Main"]
